version: "3"

services:
  app:
    build: .
    ports:
      - 3000:3000
    env_file: .env
    depends_on:
      - cache

  setup_user:
    build:
      context: .
      dockerfile: DockerfileSetupUser
    env_file: .env
    depends_on:
      - app

  cache:
    image: redis
    ports:
      - 6379:6379
