name: CI

on: [pull_request]

jobs:
  test-unit:
    strategy:
      matrix:
        go-version: [1.24.x]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
          cache: false
      - run: go test ./...
